import OBJLoader from './utils/loaders/OBJLoader'
import OBJLoader2 from './utils/loaders/OBJLoader2'
import TDSLoader from './utils/loaders/TDSLoader'
import MTLLoader from './utils/loaders/MTLLoader'
import LoaderSupport from './utils/loaders/LoaderSupport'
